"use client";
import Header from '@/Pages/Components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import SideNav from '@/Pages/Components/SideNav'
import { useState } from 'react';
import MyConnections from '@/app/connection/page';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [display,setDisplay]=useState("hidden");
  const toogleSideNav = () => {
      if(display == "hidden"){
          setDisplay("block")
      }else{
          setDisplay("hidden")
      }
  }
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
      </head>
      <body className={inter.className}>
      <div className='flex px-2  pt-2 w-screen'>
        <div className={`w-[18vw] ${display} lg:inline-block`}><SideNav toogle={toogleSideNav}/></div>
      <div className='w-screen xl:w-[82vw] xl:pr-12'>
        <Header  toogle={toogleSideNav}/>
        {children}
      </div> 
    </div>
        </body>
    </html>
  )
}
